services:

  traefik:
    image: traefik:latest

    restart: unless-stopped

    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web

      - --certificatesresolvers.letsencrypt.acme.email=TU_CORREO@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - traefik-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:8

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend

    restart: unless-stopped

    expose:
      - "8080"

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      PORT: ${PORT}

      STORAGE_PATH: ${STORAGE_PATH}

    volumes:
      - backend_storage:/app/storage

    depends_on:
      - mysql

    labels:
      - traefik.enable=true

      # GO API
      - traefik.http.routers.backend.rule=Host(`api.zcontables.net`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt

      - traefik.http.services.backend.loadbalancer.server.port=8080

  frontend:
    build:
      context: ./frontend
      args:
        BUILD_COMMIT: ${BUILD_COMMIT:-local}

    restart: unless-stopped

    expose:
      - "3000"

    depends_on:
      - backend

    labels:
      - traefik.enable=true

      # REACT FRONTEND
      - traefik.http.routers.frontend.rule=Host(`zcontables.net`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt

      - traefik.http.services.frontend.loadbalancer.server.port=3000

volumes:
  mysql_data:
  traefik-letsencrypt:
  backend_storage: