package routes

import (
	"miappfiber/controllers"
	"miappfiber/middleware"
	"miappfiber/rbac"

	"github.com/gofiber/fiber/v3"
)

func Setup(app *fiber.App) {
	authCtrl := controllers.NewAuthController()
	meCtrl := controllers.NewMeController()
	dashboardCtrl := controllers.NewDashboardController()
	companyCtrl := controllers.NewCompanyController()
	contactCtrl := controllers.NewContactController()
	documentCtrl := controllers.NewDocumentController()
	paymentCtrl := controllers.NewPaymentController()
	configCtrl := controllers.NewConfigController()
	activityRuleCtrl := controllers.NewActivityRuleController()
	fiscalReceiptCtrl := controllers.NewFiscalReceiptController()
	fiscalSeriesCtrl := controllers.NewFiscalDocumentSeriesController()
	posSaleCtrl := controllers.NewPosSaleController()
	userCtrl := controllers.NewUserController()
	roleCtrl := controllers.NewRoleController()
	reportCtrl := controllers.NewReportController()
	planCatCtrl := controllers.NewPlanCategoryController()
	subPlanCtrl := controllers.NewSubscriptionPlanController()
	liqCtrl := controllers.NewLiquidationController()
	productCtrl := controllers.NewProductController()
	productCatCtrl := controllers.NewProductCategoryController()
	taxSettleCtrl := controllers.NewTaxSettlementController()
	supervisorCtrl := controllers.NewSupervisorController()
	calendarCtrl := controllers.NewFinanceCalendarController()
	activityTplCtrl := controllers.NewActivityTemplateController()
	credCtrl := controllers.NewCompanyAccessCredentialController()

	app.Post("/api/login", authCtrl.LoginAPI)

	api := app.Group("/api", middleware.JWTProtected())
	api.Get("/dashboard", middleware.RequirePermission(rbac.DashboardView), dashboardCtrl.HomeAPI)
	api.Get("/logout", authCtrl.LogoutAPI)

	api.Get("/me/permissions", meCtrl.PermissionsAPI)

	api.Get("/roles", middleware.RequirePermission(rbac.RBACRolesView), roleCtrl.ListAPI)
	api.Get("/roles/default", middleware.RequirePermission(rbac.RBACRolesView), roleCtrl.GetDefaultAPI)
	api.Post("/roles", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.CreateAPI)
	api.Get("/roles/:id", middleware.RequirePermission(rbac.RBACRolesView), roleCtrl.GetAPI)
	api.Put("/roles/:id/default", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.SetDefaultAPI)
	api.Post("/roles/:id/clone", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.CloneAPI)
	api.Put("/roles/:id", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.UpdateAPI)
	api.Delete("/roles/:id", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.DeleteAPI)
	api.Get("/permissions/catalog", middleware.RequirePermission(rbac.RBACPermissionsCatalog), roleCtrl.CatalogAPI)
	api.Put("/roles/:id/permissions", middleware.RequirePermission(rbac.RBACRolesManage), roleCtrl.ReplacePermissionsAPI)

	// Configuración API
	api.Get("/firm-config", middleware.RequirePermission(rbac.SettingsFirmView), configCtrl.FirmConfigAPI)
	api.Get("/firm-config/branding", middleware.RequirePermission(rbac.SettingsFirmBrandingView), configCtrl.FirmBrandingAPI)
	api.Put("/firm-config", middleware.RequirePermission(rbac.SettingsFirmUpdate), configCtrl.UpdateFirmConfigAPI)
	api.Post("/firm-config/logo", middleware.RequirePermission(rbac.SettingsFirmUploadLogo), configCtrl.UploadFirmLogoAPI)
	api.Post("/firm-config/statement-bank-logo", middleware.RequirePermission(rbac.SettingsFirmUploadBankLogo), configCtrl.UploadStatementBankLogoAPI)
	api.Post("/firm-config/statement-payment-qr", middleware.RequirePermission(rbac.SettingsFirmUploadPaymentQR), configCtrl.UploadStatementPaymentQrAPI)

	api.Get("/activity-rules", middleware.RequirePermission(rbac.SettingsFirmView), activityRuleCtrl.ListAPI)
	api.Get("/activity-rules/:id", middleware.RequirePermission(rbac.SettingsFirmView), activityRuleCtrl.GetAPI)
	api.Get("/activity-rules/:id/audits", middleware.RequirePermission(rbac.SettingsFirmView), activityRuleCtrl.AuditsAPI)
	api.Post("/activity-rules", middleware.RequirePermission(rbac.SettingsFirmUpdate), activityRuleCtrl.CreateAPI)
	api.Put("/activity-rules/:id", middleware.RequirePermission(rbac.SettingsFirmUpdate), activityRuleCtrl.UpdateAPI)
	api.Delete("/activity-rules/:id", middleware.RequirePermission(rbac.SettingsFirmUpdate), activityRuleCtrl.DeleteAPI)

	api.Get("/activity-templates", middleware.RequirePermission(rbac.SettingsFirmView), activityTplCtrl.ListAPI)
	api.Patch("/activity-templates/:id/activity-rule", middleware.RequirePermission(rbac.SettingsFirmUpdate), activityTplCtrl.SetActivityRuleAPI)

	// Companies
	api.Post("/companies/validate-ruc", middleware.RequirePermission(rbac.CompaniesValidateRUC), companyCtrl.ValidateRUCAPI)
	api.Post("/companies/validate-dni", middleware.RequirePermission(rbac.CompaniesValidateDNI), companyCtrl.ValidateDNIAPI)
	api.Get("/companies/next-internal-code", middleware.RequirePermission(rbac.CompaniesNextCode), companyCtrl.NextInternalCodeAPI)
	api.Get("/companies/import/template", middleware.RequirePermission(rbac.CompaniesImportTemplate), companyCtrl.ImportTemplateAPI)
	api.Post("/companies/import", middleware.RequirePermission(rbac.CompaniesImportSpreadsheet), companyCtrl.ImportCompaniesAPI)
	api.Get("/companies", middleware.RequirePermission(rbac.CompaniesView), companyCtrl.ListAPI)
	api.Get("/companies/:id", middleware.RequirePermission(rbac.CompaniesView), companyCtrl.GetAPI)
	api.Get("/companies/:id/statement", middleware.RequirePermission(rbac.CompaniesView), companyCtrl.StatementAPI)
	api.Post("/companies", middleware.RequirePermission(rbac.CompaniesCreate), companyCtrl.CreateAPI)
	api.Put("/companies/:id", middleware.RequirePermission(rbac.CompaniesUpdate), companyCtrl.UpdateAPI)
	api.Put("/companies/:id/convert-to-studio", middleware.RequirePermission(rbac.CompaniesConvertToStudio), companyCtrl.ConvertToStudioAPI)
	api.Patch("/companies/:id/status", middleware.RequirePermission(rbac.CompaniesStatus), companyCtrl.PatchStatusAPI)
	api.Delete("/companies/:id", middleware.RequirePermission(rbac.CompaniesDelete), companyCtrl.DeleteAPI)

	// Contacts
	api.Get("/companies/:companyID/contacts", middleware.RequirePermission(rbac.ContactsView), contactCtrl.ListByCompanyAPI)
	api.Get("/companies/:companyID/contacts/:id", middleware.RequirePermission(rbac.ContactsView), contactCtrl.GetAPI)
	api.Post("/companies/:companyID/contacts", middleware.RequirePermission(rbac.ContactsCreate), contactCtrl.CreateAPI)
	api.Put("/companies/:companyID/contacts/:id", middleware.RequirePermission(rbac.ContactsUpdate), contactCtrl.UpdateAPI)
	api.Delete("/companies/:companyID/contacts/:id", middleware.RequirePermission(rbac.ContactsDelete), contactCtrl.DeleteAPI)

	// Documents
	api.Get("/documents", middleware.RequirePermission(rbac.DocumentsView), documentCtrl.ListAPI)
	api.Get("/documents/:id", middleware.RequirePermission(rbac.DocumentsView), documentCtrl.GetAPI)
	api.Post("/documents", middleware.RequirePermission(rbac.DocumentsCreate), documentCtrl.CreateAPI)
	api.Put("/documents/:id", middleware.RequirePermission(rbac.DocumentsUpdate), documentCtrl.UpdateAPI)
	api.Delete("/documents/:id", middleware.RequirePermission(rbac.DocumentsDelete), documentCtrl.DeleteAPI)

	// Payments
	api.Get("/payments", middleware.RequirePermission(rbac.PaymentsView), paymentCtrl.ListAPI)
	api.Get("/payments/:id", middleware.RequirePermission(rbac.PaymentsView), paymentCtrl.GetAPI)
	api.Post("/payments", middleware.RequirePermission(rbac.PaymentsCreate), paymentCtrl.CreateAPI)
	api.Post("/payments/:id/issue-comprobante", middleware.RequirePermission(rbac.PaymentsIssueComprobante), paymentCtrl.IssueComprobanteAPI)
	api.Post("/payments/:id/issue-tukifac", middleware.RequirePermission(rbac.PaymentsIssueComprobante), paymentCtrl.IssueTukifacAPI)
	api.Put("/payments/:id", middleware.RequirePermission(rbac.PaymentsUpdate), paymentCtrl.UpdateAPI)
	api.Delete("/payments/:id", middleware.RequirePermission(rbac.PaymentsDelete), paymentCtrl.DeleteAPI)
	api.Post("/payments/upload-attachment", middleware.RequirePermission(rbac.PaymentsUploadAttachment), paymentCtrl.UploadAttachmentAPI)

	// Users API
	api.Get("/users", middleware.RequirePermission(rbac.UsersView), userCtrl.ListAPI)
	api.Get("/users/:id", middleware.RequirePermission(rbac.UsersView), userCtrl.GetAPI)
	api.Post("/users", middleware.RequirePermission(rbac.UsersCreate), userCtrl.CreateAPI)
	api.Put("/users/:id", middleware.RequirePermission(rbac.UsersUpdate), userCtrl.UpdateAPI)
	api.Delete("/users/:id", middleware.RequirePermission(rbac.UsersDelete), userCtrl.DeleteAPI)

	// Reports API
	api.Get("/reports/financial", middleware.RequirePermission(rbac.ReportsFinancialView), reportCtrl.FinancialSummaryAPI)
	api.Get("/reports/debts", middleware.RequirePermission(rbac.ReportsFinancialView), reportCtrl.DebtsReportAPI)

	// Series y comprobantes fiscales (local)
	api.Get("/fiscal-document-series", middleware.RequirePermission(rbac.FiscalSeriesView), fiscalSeriesCtrl.ListAPI)
	api.Get("/fiscal-document-series/:id", middleware.RequirePermission(rbac.FiscalSeriesView), fiscalSeriesCtrl.GetAPI)
	api.Post("/fiscal-document-series", middleware.RequirePermission(rbac.FiscalSeriesManage), fiscalSeriesCtrl.CreateAPI)
	api.Put("/fiscal-document-series/:id", middleware.RequirePermission(rbac.FiscalSeriesManage), fiscalSeriesCtrl.UpdateAPI)
	api.Get("/document/series", middleware.RequirePermission(rbac.FiscalSeriesView), fiscalSeriesCtrl.ListAPI)
	api.Get("/sale-note/series", middleware.RequirePermission(rbac.FiscalSeriesView), fiscalSeriesCtrl.ListAPI)

	api.Get("/fiscal-receipts", middleware.RequirePermission(rbac.FiscalReceiptsList), fiscalReceiptCtrl.ListFiscalReceiptsAPI)
	api.Get("/fiscal-receipts/:id", middleware.RequirePermission(rbac.FiscalReceiptsList), fiscalReceiptCtrl.GetAPI)
	api.Get("/tukifac/fiscal-receipts", middleware.RequirePermission(rbac.FiscalReceiptsList), fiscalReceiptCtrl.ListFiscalReceiptsAPI)
	api.Get("/tukifac/fiscal-receipts/:id", middleware.RequirePermission(rbac.FiscalReceiptsList), fiscalReceiptCtrl.GetAPI)
	api.Post("/fiscal-receipts/:id/create-payment", middleware.RequirePermission(rbac.FiscalReceiptsCreatePayment), fiscalReceiptCtrl.CreatePaymentFromReceiptAPI)
	api.Post("/tukifac/fiscal-receipts/:id/create-payment", middleware.RequirePermission(rbac.FiscalReceiptsCreatePayment), fiscalReceiptCtrl.CreatePaymentFromReceiptAPI)
	api.Post("/fiscal-receipts/:id/link-payment", middleware.RequirePermission(rbac.FiscalReceiptsLinkPayment), fiscalReceiptCtrl.LinkReceiptAPI)
	api.Post("/tukifac/fiscal-receipts/:id/link-payment", middleware.RequirePermission(rbac.FiscalReceiptsLinkPayment), fiscalReceiptCtrl.LinkReceiptAPI)
	api.Patch("/fiscal-receipts/:id/tax-settlement", middleware.RequirePermission(rbac.FiscalReceiptsPatchTax), fiscalReceiptCtrl.PatchReceiptTaxSettlementAPI)
	api.Patch("/tukifac/fiscal-receipts/:id/tax-settlement", middleware.RequirePermission(rbac.FiscalReceiptsPatchTax), fiscalReceiptCtrl.PatchReceiptTaxSettlementAPI)
	api.Post("/fiscal-receipts/:id/discard", middleware.RequirePermission(rbac.FiscalReceiptsDiscard), fiscalReceiptCtrl.DiscardReceiptAPI)
	api.Post("/tukifac/fiscal-receipts/:id/discard", middleware.RequirePermission(rbac.FiscalReceiptsDiscard), fiscalReceiptCtrl.DiscardReceiptAPI)

	// Venta rápida / POS
	api.Post("/pos/sales", middleware.RequirePermission(rbac.SalesEmit), posSaleCtrl.IssueAPI)
	api.Post("/pos/upload-payment-proof", middleware.RequirePermission(rbac.SalesEmit), posSaleCtrl.UploadPaymentProofAPI)
	api.Get("/pos/sales", middleware.RequirePermission(rbac.SalesHistory), posSaleCtrl.ListAPI)
	api.Get("/pos/sales/:id", middleware.RequirePermission(rbac.SalesHistory), posSaleCtrl.GetAPI)
	api.Get("/pos/companies", middleware.RequirePermission(rbac.SalesCompaniesPick), posSaleCtrl.ListCompaniesAPI)
	api.Post("/pos/companies", middleware.RequirePermission(rbac.SalesCompaniesPick), posSaleCtrl.CreateQuickCompanyAPI)
	api.Post("/pos/companies/validate-ruc", middleware.RequirePermission(rbac.SalesCompaniesPick), companyCtrl.ValidateRUCAPI)
	api.Post("/pos/companies/validate-dni", middleware.RequirePermission(rbac.SalesCompaniesPick), companyCtrl.ValidateDNIAPI)
	api.Get("/pos/products", middleware.RequirePermission(rbac.SalesCatalogPick), posSaleCtrl.ListProductsAPI)
	api.Get("/pos/document-series", middleware.RequirePermission(rbac.SalesEmit), fiscalSeriesCtrl.ListAPI)

	// Productos y servicios
	api.Get("/products", middleware.RequirePermission(rbac.ProductsView), productCtrl.ListAPI)
	api.Get("/products/:id", middleware.RequirePermission(rbac.ProductsView), productCtrl.GetAPI)
	api.Post("/products", middleware.RequirePermission(rbac.ProductsCreate), productCtrl.CreateAPI)
	api.Put("/products/:id", middleware.RequirePermission(rbac.ProductsUpdate), productCtrl.UpdateAPI)
	api.Delete("/products/:id", middleware.RequirePermission(rbac.ProductsDelete), productCtrl.DeleteAPI)
	api.Get("/product-categories", middleware.RequirePermission(rbac.ProductCategoriesView), productCatCtrl.ListAPI)
	api.Post("/product-categories", middleware.RequirePermission(rbac.ProductCategoriesCreate), productCatCtrl.CreateAPI)

	// Planes y liquidación
	api.Get("/plan-categories", middleware.RequirePermission(rbac.PlanCategoriesView), planCatCtrl.ListAPI)
	api.Get("/plan-categories/:id", middleware.RequirePermission(rbac.PlanCategoriesView), planCatCtrl.GetAPI)
	api.Post("/plan-categories", middleware.RequirePermission(rbac.PlanCategoriesCreate), planCatCtrl.CreateAPI)
	api.Put("/plan-categories/:id", middleware.RequirePermission(rbac.PlanCategoriesUpdate), planCatCtrl.UpdateAPI)
	api.Delete("/plan-categories/:id", middleware.RequirePermission(rbac.PlanCategoriesDelete), planCatCtrl.DeleteAPI)

	api.Get("/subscription-plans", middleware.RequirePermission(rbac.SubscriptionPlansView), subPlanCtrl.ListAPI)
	api.Get("/subscription-plans/:id", middleware.RequirePermission(rbac.SubscriptionPlansView), subPlanCtrl.GetAPI)
	api.Post("/subscription-plans", middleware.RequirePermission(rbac.SubscriptionPlansCreate), subPlanCtrl.CreateAPI)
	api.Put("/subscription-plans/:id", middleware.RequirePermission(rbac.SubscriptionPlansUpdate), subPlanCtrl.UpdateAPI)
	api.Put("/subscription-plans/:id/tiers", middleware.RequirePermission(rbac.SubscriptionPlansTiers), subPlanCtrl.ReplaceTiersAPI)
	api.Delete("/subscription-plans/:id", middleware.RequirePermission(rbac.SubscriptionPlansDelete), subPlanCtrl.DeleteAPI)

	api.Post("/liquidation/run", middleware.RequirePermission(rbac.LiquidationRun), liqCtrl.RunLiquidationAPI)

	// Liquidaciones de impuestos
	api.Get("/companies/:id/settlements/preview", middleware.RequirePermission(rbac.TaxSettlementsPreview), taxSettleCtrl.PreviewSettlementsAPI)
	api.Get("/companies/:id/settlements/pending-from-closed", middleware.RequirePermission(rbac.TaxSettlementsPreview), taxSettleCtrl.PendingFromClosedAPI)
	api.Get("/tax-settlements", middleware.RequirePermission(rbac.TaxSettlementsList), taxSettleCtrl.ListAPI)
	api.Post("/tax-settlements", middleware.RequirePermission(rbac.TaxSettlementsCreate), taxSettleCtrl.CreateAPI)
	api.Get("/tax-settlements/:id/payment-suggestions", middleware.RequirePermission(rbac.TaxSettlementsPaymentSuggestions), taxSettleCtrl.PaymentSuggestionsAPI)
	api.Get("/tax-settlements/:id/debts-context", middleware.RequirePermission(rbac.TaxSettlementsView), taxSettleCtrl.DebtsContextAPI)
	api.Post("/tax-settlements/:id/link-debt", middleware.RequirePermission(rbac.TaxSettlementsUpdate), taxSettleCtrl.LinkDebtAPI)
	api.Post("/tax-settlements/debts/:documentId/writeoff", middleware.RequirePermission(rbac.TaxSettlementsUpdate), taxSettleCtrl.WriteOffDebtAPI)
	api.Get("/tax-settlements/:id", middleware.RequirePermission(rbac.TaxSettlementsView), taxSettleCtrl.GetAPI)
	api.Put("/tax-settlements/:id", middleware.RequirePermission(rbac.TaxSettlementsUpdate), taxSettleCtrl.UpdateAPI)
	api.Post("/tax-settlements/:id/revert-to-draft", middleware.RequirePermission(rbac.TaxSettlementsUpdate), taxSettleCtrl.RevertToDraftAPI)
	api.Post("/tax-settlements/:id/emit", middleware.RequirePermission(rbac.TaxSettlementsEmit), taxSettleCtrl.EmitAPI)
	api.Post("/tax-settlements/:id/close", middleware.RequirePermission(rbac.TaxSettlementsUpdate), taxSettleCtrl.CloseAPI)
	api.Delete("/tax-settlements/:id", middleware.RequirePermission(rbac.TaxSettlementsDelete), taxSettleCtrl.DeleteAPI)

	// Supervisores contables
	sup := api.Group("/supervisors")
	sup.Get("/dashboard", middleware.RequirePermission(rbac.SupervisorsDashboardView), supervisorCtrl.DashboardAPI)
	sup.Get("/periods", middleware.RequirePermission(rbac.SupervisorsPeriodsView), supervisorCtrl.ListPeriodsAPI)
	sup.Post("/periods", middleware.RequirePermission(rbac.SupervisorsPeriodsCreate), supervisorCtrl.CreatePeriodAPI)
	sup.Put("/periods/:id", middleware.RequirePermission(rbac.SupervisorsPeriodsUpdate), supervisorCtrl.UpdatePeriodAPI)
	sup.Delete("/periods/:id", middleware.RequirePermission(rbac.SupervisorsPeriodsDelete), supervisorCtrl.DeletePeriodAPI)
	sup.Post("/periods/:id/close", middleware.RequirePermission(rbac.SupervisorsPeriodsClose), supervisorCtrl.ClosePeriodAPI)
	sup.Post("/periods/:id/bootstrap-controls", middleware.RequirePermission(rbac.SupervisorsPeriodsBootstrap), supervisorCtrl.BootstrapPeriodAPI)
	sup.Get("/controls", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.ListControlsAPI)
	sup.Get("/controls/:id", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.GetControlAPI)
	sup.Post("/controls", middleware.RequirePermission(rbac.SupervisorsControlsCreate), supervisorCtrl.CreateControlAPI)
	sup.Put("/controls/:id", middleware.RequirePermission(rbac.SupervisorsControlsUpdate), supervisorCtrl.UpdateControlAPI)
	sup.Post("/controls/:id/info-received", middleware.RequirePermission(rbac.SupervisorsControlsUpdate), supervisorCtrl.RegisterInfoReceivedAPI)
	sup.Delete("/controls/:id", middleware.RequirePermission(rbac.SupervisorsControlsDelete), supervisorCtrl.DeleteControlAPI)
	sup.Get("/controls/:controlId/declarations", middleware.RequirePermission(rbac.SupervisorsDeclarationsView), supervisorCtrl.ListDeclarationsAPI)
	sup.Put("/declarations/:id", middleware.RequirePermission(rbac.SupervisorsDeclarationsUpdate), supervisorCtrl.UpdateDeclarationAPI)
	sup.Post("/declarations/:id/approve", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.ApproveDeclarationAPI)
	sup.Post("/declarations/:id/observe", middleware.RequirePermission(rbac.SupervisorsDeclarationsObserve), supervisorCtrl.ObserveDeclarationAPI)
	sup.Delete("/declarations/:id", middleware.RequirePermission(rbac.SupervisorsDeclarationsDelete), supervisorCtrl.DeleteDeclarationAPI)
	sup.Get("/controls/:controlId/liquidation", middleware.RequirePermission(rbac.SupervisorsLiquidationsView), supervisorCtrl.GetLiquidationAPI)
	sup.Put("/controls/:controlId/liquidation", middleware.RequirePermission(rbac.SupervisorsLiquidationsUpdate), supervisorCtrl.UpdateLiquidationAPI)
	sup.Post("/controls/:controlId/liquidation/approve", middleware.RequirePermission(rbac.SupervisorsLiquidationsApprove), supervisorCtrl.ApproveLiquidationAPI)
	sup.Post("/controls/:controlId/liquidation/observe", middleware.RequirePermission(rbac.SupervisorsLiquidationsApprove), supervisorCtrl.ObserveLiquidationAPI)
	sup.Get("/controls/:controlId/nps", middleware.RequirePermission(rbac.SupervisorsNPSView), supervisorCtrl.ListNPSAPI)
	sup.Post("/nps", middleware.RequirePermission(rbac.SupervisorsNPSCreate), supervisorCtrl.CreateNPSAPI)
	sup.Put("/nps/:id", middleware.RequirePermission(rbac.SupervisorsNPSUpdate), supervisorCtrl.UpdateNPSAPI)
	sup.Post("/nps/:id/generate", middleware.RequirePermission(rbac.SupervisorsNPSGenerate), supervisorCtrl.GenerateNPSAPI)
	sup.Delete("/nps/:id", middleware.RequirePermission(rbac.SupervisorsNPSDelete), supervisorCtrl.DeleteNPSAPI)
	sup.Get("/reports/monthly", middleware.RequirePermission(rbac.SupervisorsReportsView), supervisorCtrl.ReportMonthlyAPI)
	sup.Get("/history", middleware.RequirePermission(rbac.SupervisorsHistoryView), supervisorCtrl.ListHistoryAPI)
	sup.Get("/observations", middleware.RequirePermission(rbac.SupervisorsObservationsView), supervisorCtrl.ListObservationsAPI)
	sup.Post("/observations", middleware.RequirePermission(rbac.SupervisorsObservationsCreate), supervisorCtrl.CreateObservationAPI)
	sup.Get("/attachments", middleware.RequirePermission(rbac.SupervisorsObservationsView), supervisorCtrl.ListAttachmentsAPI)
	sup.Post("/attachments/upload", middleware.RequirePermission(rbac.SupervisorsAttachmentsUpload), supervisorCtrl.UploadAttachmentAPI)
	sup.Get("/notifications", middleware.RequirePermission(rbac.SupervisorsNotificationsView), supervisorCtrl.ListNotificationsAPI)
	sup.Post("/notifications/:id/read", middleware.RequirePermission(rbac.SupervisorsNotificationsView), supervisorCtrl.MarkNotificationReadAPI)
	sup.Post("/nps/:id/register-payment", middleware.RequirePermission(rbac.SupervisorsNPSRegisterPayment), supervisorCtrl.RegisterNPSPaymentAPI)
	sup.Get("/activity-modules/sunat-inbox", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.SunatInboxListAPI)
	sup.Get("/activity-modules/sunat-inbox/companies/:companyId", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.SunatInboxDetailAPI)
	sup.Post("/activity-modules/sunat-inbox/companies/:companyId/slots/:slotIndex/upload", middleware.RequirePermission(rbac.SupervisorsAttachmentsUpload), supervisorCtrl.SunatInboxUploadAPI)
	sup.Post("/activity-modules/sunat-inbox/slots/:slotId/verify", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.SunatInboxVerifySlotAPI)
	sup.Get("/activity-modules/detracciones", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.DetraccionesListAPI)
	sup.Get("/activity-modules/detracciones/companies/:companyId", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.DetraccionesDetailAPI)
	sup.Post("/activity-modules/detracciones/companies/:companyId/upload", middleware.RequirePermission(rbac.SupervisorsAttachmentsUpload), supervisorCtrl.DetraccionesUploadAPI)
	sup.Post("/activity-modules/detracciones/declarations/:declarationId/verify", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.DetraccionesVerifyAPI)
	sup.Post("/activity-modules/detracciones/declarations/:declarationId/validate", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.DetraccionesValidateAPI)
	sup.Put("/activity-modules/detracciones/declarations/:declarationId/status", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.DetraccionesSetStatusAPI)
	// Alias legacy F4 (deprecar en próxima versión)
	sup.Get("/activity-modules/distractions", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.DetraccionesListAPI)
	sup.Get("/activity-modules/distractions/companies/:companyId", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.DetraccionesDetailAPI)
	sup.Post("/activity-modules/distractions/declarations/:declarationId/validate", middleware.RequirePermission(rbac.SupervisorsDeclarationsApprove), supervisorCtrl.DetraccionesValidateAPI)
	sup.Get("/activity-modules/pdt-601", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.Pdt601ListAPI)
	sup.Get("/activity-modules/pdt-601/companies/:companyId", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.Pdt601DetailAPI)
	sup.Get("/activity-modules/pdt-621", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.Pdt621ListAPI)
	sup.Get("/activity-modules/pdt-621/companies/:companyId", middleware.RequirePermission(rbac.SupervisorsControlsView), supervisorCtrl.Pdt621DetailAPI)
	sup.Get("/tax-settlements/drafts-by-companies", middleware.RequirePermission(rbac.SupervisorsLiquidationsView), supervisorCtrl.TaxSettlementDraftsByCompaniesAPI)
	sup.Get("/tax-settlements/:id", middleware.RequirePermission(rbac.SupervisorsLiquidationsView), supervisorCtrl.GetTaxSettlementAPI)
	sup.Post("/tax-settlements", middleware.RequirePermission(rbac.SupervisorsLiquidationsCreate), supervisorCtrl.CreateTaxSettlementAPI)
	sup.Put("/tax-settlements/:id", middleware.RequirePermission(rbac.SupervisorsLiquidationsUpdate), supervisorCtrl.UpdateTaxSettlementAPI)

	// Catálogo de actividades (Finanzas / Calendario)
	tpl := api.Group("/finance/activity-templates")
	tpl.Get("/", middleware.RequirePermission(rbac.FinanceCalendarView), activityTplCtrl.ListAPI)
	tpl.Get("/next-code", middleware.RequirePermission(rbac.FinanceCalendarManage), activityTplCtrl.PreviewCodeAPI)
	tpl.Get("/:id", middleware.RequirePermission(rbac.FinanceCalendarView), activityTplCtrl.GetAPI)
	tpl.Post("/", middleware.RequirePermission(rbac.FinanceCalendarManage), activityTplCtrl.CreateAPI)
	tpl.Put("/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), activityTplCtrl.UpdateAPI)
	tpl.Patch("/:id/active", middleware.RequirePermission(rbac.FinanceCalendarManage), activityTplCtrl.SetActiveAPI)
	tpl.Delete("/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), activityTplCtrl.DeleteAPI)

  // Calendario contable global (lectura: cualquier usuario autenticado; gestión: finance.calendar_manage)
	cal := api.Group("/finance/calendar")
	cal.Get("/", calendarCtrl.ListAPI)
	cal.Get("/activities/:activityId/compliance", calendarCtrl.ComplianceAPI)
	cal.Get("/:periodYm", calendarCtrl.GetAPI)
	cal.Post("/duplicate", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.DuplicateAPI)
	cal.Post("/", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.CreateAPI)
	cal.Put("/months/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.UpdateAPI)
	cal.Put("/months/:id/close", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.CloseAPI)
	cal.Put("/months/:id/reopen", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.ReopenAPI)
	cal.Delete("/months/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.DeleteAPI)
	cal.Post("/months/:calendarId/marks", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.CreateMarkAPI)
	cal.Delete("/marks/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.DeleteMarkAPI)
	cal.Post("/months/:calendarId/activities", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.CreateActivityAPI)
	cal.Put("/activities/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.UpdateActivityAPI)
	cal.Delete("/activities/:id", middleware.RequirePermission(rbac.FinanceCalendarManage), calendarCtrl.DeleteActivityAPI)

	// Claves de acceso por empresa (lectura: autenticado; edición/import: permisos finance.company_credentials_*)
	creds := api.Group("/finance/company-credentials")
	creds.Get("/", credCtrl.ListAPI)
	creds.Get("/filter-facets", credCtrl.FilterFacetsAPI)
	creds.Get("/:companyId", credCtrl.GetAPI)
	creds.Get("/import/template", middleware.RequirePermission(rbac.CompanyCredentialsImport), credCtrl.ImportTemplateAPI)
	creds.Post("/import", middleware.RequirePermission(rbac.CompanyCredentialsImport), credCtrl.ImportAPI)
	creds.Put("/:companyId", middleware.RequirePermission(rbac.CompanyCredentialsManage), credCtrl.UpdateAPI)
}
